Assign project draft publish statuses
AtlasOfLivingAustralia/biocollect pull request #1400
Opened 2022-02-17 23:06 UTC by chamaliperera512

2022-02-21 23:34 UTC, temi requested changes
Reviewed. I am available to discuss further.

2022-02-21 23:34 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +             activities     : projectActivities
`activities` needs renaming.

2022-02-21 23:34 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +            if (isAlaAdmin)
It looks to me ALA admin can only see published projects in their user page. is the logic correct?

2022-02-21 23:34 UTC, temi commented on grails-app/services/au/org/ala/biocollect/merit/ProjectService.groovy
> +                        int facetIndex = facets.size()
Any reason why this code has changed? It is supposed to replace special facets at the index found in `hubFacets`.

2022-02-21 23:34 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +            if (isAlaAdmin)
The code needs to satisfy the following conditions
1. ALA admin can see published and unpublished projects on project finder.
2. Regular users should only see published projects only.
3. Regular users when viewing `My projects` should be able to see their projects that are both published and unpublished.

2022-03-02 06:04 UTC, temi requested changes
I am happy to discuss this further.

2022-03-02 06:04 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +            if (!fq.contains('projLifecycleStatus:published'))
Are you trying to get both published and unpublished here? Not adding any `fq` will get both projects.

2022-03-03 23:05 UTC, chamaliperera512 commented on grails-app/services/au/org/ala/biocollect/merit/ProjectService.groovy
> +                        def item =  hubFacets[index - 1]
Handled

2022-03-03 23:05 UTC, chamaliperera512 commented on grails-app/services/au/org/ala/biocollect/merit/ProjectService.groovy
> +                        if (facetIndex >= 0)
Handled

2022-03-03 23:05 UTC, chamaliperera512 commented on grails-app/assets/javascripts/projects.js
> +    self.checkPublishedProjectActivities = function (activities) {
Renamed

2022-03-03 23:12 UTC, chamaliperera512 commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +            def user = userService.getUser()
Done

2022-03-06 22:52 UTC, temi requested changes

2022-03-06 22:52 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +    def removeFacetsFromProjectFinderPage(List facets) {
make this method private.

2022-03-06 22:52 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +                int index = facets.findIndexOf { it == facetsToRemove[i] }
you can replace this code with `facets.remove(facetsToRemove[i])`

2022-03-06 22:52 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +        if (facets.size() > 0) {
you can replace this code with `facets.join(',')`

2022-03-06 22:52 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
> +    def removeFacetsFromProjectFinderPage(List facets) {
Also add some comments to describe what this method does.

2022-03-07 00:11 UTC, temi requested changes

2022-03-07 00:11 UTC, temi commented on grails-app/controllers/au/org/ala/biocollect/merit/ProjectController.groovy
>              for (int i = 0; i < facetsToRemove.size(); i++) {
you can remove the whole block and add `facets.removeAll(facetsToRemove)`

2022-03-07 00:45 UTC, temi approved these changes
Looks good

2022-05-18 13:49 UTC, merged